In [1]:
a1 = 1
a2 = 5
a3 = 10

In [2]:
l1 = [1,4,9]
l2 = [1,"a",3]

In [3]:
l1[1]

4

In [4]:
l1[0]

1

In [5]:
l1[0:2]

[1, 4]

In [6]:
l1.append(3)

In [7]:
l1

[1, 4, 9, 3]

In [8]:
l2.remove('a')

In [9]:
l2

[1, 3]

In [10]:
l1.sort()
l1

[1, 3, 4, 9]

In [11]:
l1[3]

9

In [12]:
l1[3] = 10

In [13]:
l1

[1, 3, 4, 10]

In [14]:
l3 = [[1,2,3],[1,4,9]]

In [16]:
l3[1][0]

1

In [17]:
l1

[1, 3, 4, 10]

In [18]:
l1 * 2

[1, 3, 4, 10, 1, 3, 4, 10]

In [19]:
l1 + 2

TypeError: can only concatenate list (not "int") to list

In [20]:
l1 +[2]

[1, 3, 4, 10, 2]

In [21]:
import numpy as np

In [24]:
a1 = np.array([1,4,9])
a2 = np.array([1,"a",3])
a3 = np.array([[1,2,3],[1,4,9]])

In [25]:
a3

array([[1, 2, 3],
       [1, 4, 9]])

In [26]:
a1[1]

4

In [27]:
a1[:2]

array([1, 4])

In [28]:
a2

array(['1', 'a', '3'], dtype='<U21')

In [30]:
a3[0,2]

3

In [31]:
a3

array([[1, 2, 3],
       [1, 4, 9]])

In [32]:
np.append(a1, 5)

array([1, 4, 9, 5])

In [34]:
a1

array([1, 4, 9])

In [35]:
a1 = np.append(a1, 5)

In [36]:
a1

array([1, 4, 9, 5])

In [37]:
a1 = np.append(a1, np.array([5,6]))

In [38]:
a1

array([1, 4, 9, 5, 5, 6])

In [39]:
a3

array([[1, 2, 3],
       [1, 4, 9]])

In [44]:
np.append(a3, np.array([[1,8,27]]), axis=0)

array([[ 1,  2,  3],
       [ 1,  4,  9],
       [ 1,  8, 27]])

In [46]:
np.append(a3, np.array([[4],[6]]), axis=1)

array([[1, 2, 3, 4],
       [1, 4, 9, 6]])

In [48]:
a1

array([1, 4, 9, 5, 5, 6])

In [47]:
a1 * 2

array([ 2,  8, 18, 10, 10, 12])

In [49]:
a3 + 2

array([[ 3,  4,  5],
       [ 3,  6, 11]])