## Defining a vector

In [3]:
import numpy as np
x = [1,2,3]
vector = np.array(x)
vector

array([1, 2, 3])

In [4]:
vector.ndim

1

In [5]:
vector.shape

(3,)

## Arithmetic operations on vectors

In [9]:
a = np.random.randint(10,50, size=5)
b = np.random.randint(25,75, size=5)

print(a)
print(b)
c = a + b
print(c)

[36 42 22 23 17]
[26 54 45 43 73]
[62 96 67 66 90]
