## Defining a vector

In [1]:
import numpy as np
x = [1,2,3]
vector = np.array(x)
vector

array([1, 2, 3])

In [2]:
vector.ndim

1

In [3]:
vector.shape

(3,)

## Arithmetic operations on vectors

In [4]:
a = np.random.randint(10,50, size=5)
b = np.random.randint(25,75, size=5)

print(a)
print(b)
c = a + b
print(c)

[25 14 37 27 22]
[57 52 69 45 72]
[ 82  66 106  72  94]


In [5]:
a = np.random.randint(10,50, size=5)
b = np.random.randint(25,75, size=5)

print(a)
print(b)
c = a - b
print("Difference: ", c)

[31 30 33 16 37]
[64 74 61 54 55]
Difference:  [-33 -44 -28 -38 -18]


In [6]:
a = np.random.randint(10,50, size=5)
b = np.random.randint(25,75, size=5)

print(a)
print(b)
c = a * b
print("Multiplication: ", c)

[25 38 14 32 30]
[68 29 49 33 41]
Multiplication:  [1700 1102  686 1056 1230]


In [7]:
a = np.random.randint(10,50, size=5)
b = np.random.randint(25,75, size=5)

print(a)
print(b)
c = a / b
print("Division: ", c)

[21 10 40 19 36]
[64 49 40 70 25]
Division:  [0.328125   0.20408163 1.         0.27142857 1.44      ]


## Dot product

In [9]:
a = np.random.randint(10,50, size=5)
b = np.random.randint(25,75, size=5)

print(a)
print(b)

[49 29 23 16 48]
[73 55 31 37 67]


In [11]:
vector_dot = a.dot(b)
vector_dot

9693

In [14]:
x = np.arange(5,10)
y = np.arange(5)

print(x)
print(y)

vector_dot = x.dot(y)
print("dot product: ", vector_dot)

[5 6 7 8 9]
[0 1 2 3 4]
dot product:  80


## Vector scalar multiplication

In [15]:
x = np.arange(5,10)

In [17]:
vs = 3 * x
print("vector scalar multiplication: ", vs)

vector scalar multiplication:  [15 18 21 24 27]


In [18]:
x

array([5, 6, 7, 8, 9])